# -*- coding: utf-8 -*-
# @Author  : itswcg
# @File    : video-api.http
# @Time    : 18-12-20 上午11:12
# @Blog    : https://blog.itswcg.com
# @github  : https://github.com/itswcg

# PyCharm http client

### 登录
POST {{base_url}}/user/
Accept: application/json
Content-Type: application/json

{
  "username": "wcg",
  "password": "itswcg"
}

### 获取用户信息
GET {{base_url}}/user/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

### 更新用户信息
PATCH {{base_url}}/user/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "password": "itswcg",
  "avatar": "http://blog.itswcg.com",
  "phone": "18502860494",
  "email": "itswcg@gmail.com"
}

### 获取我的视频
GET {{base_url}}/my-video/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

### 上传视频
POST {{base_url}}/my-video/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "name": "大尺度电影",
  "video_url": "http://blog.itswcg.com",
  "cover_url": "http://blog.itswcg.com"
}

### 获取推荐视频
GET {{base_url}}/video/?type=recommend
Accept: application/json
Content-Type: application/json

### 获取最近下载视频
GET {{base_url}}/video/?type=recent
Accept: application/json
Content-Type: application/json

### 获取单个视频
GET {{base_url}}/video/?video_id=1
Accept: application/json
Content-Type: application/json

### 获取我的任务
GET {{base_url}}/task/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

### 创建任务
POST {{base_url}}/task/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "name": "下载视频任务1"
}

### 获取我的通知
GET {{base_url}}/notice/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

### 标记通知为已读
POST {{base_url}}/notice/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "type": "single",
  "notice_id": 1
}

### 标记全部通知为已读
POST {{base_url}}/notice/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "type": "all"
}

### 评论
POST {{base_url}}/comment/
Accept: application/json
Content-Type: application/json
Authorization: Token {{user_token}}

{
  "video_id": 1,
  "content": "nice"
}

### 点赞
POST {{base_url}}/like/
Accept: application/json
Content-Type: application/json

{
  "video_id": 2
}

###

